package com.amazingmvprules.domain.util;

public class StubData {

  public static final String TECHNO = "";

  public static final String[] HOUSE_ARRAY = { "Acid House","Electro House","Deep House","G House","Tech House", };

  public static final String[] TECHNO_ARRAY = { "Acid Techno","Detroit Techno","Minimal Techno","Techno" };

  public static final String[] HOUSE_IMAGE = {
      "http://www.vintagesynth.com/roland/images/tb303big.jpg",
      "https://staging-thump-images.vice.com/images/2015/1/27/tresors-founder-wants-to-build-a-berlin-style-techno-club-in-detroit-does-the-city-need-it-1422362657487.jpg",
      "http://www.that-dj.com/wp-content/uploads/image/Deep%20Techno%20Club%20Industrial.jpg",
      "http://1.bp.blogspot.com/-59cMgzzhCwQ/URK9gztFiUI/AAAAAAAADz4/2rHQHYaR_Ek/s1600/IMG_7796.jpg",
      "http://1.bp.blogspot.com/-59cMgzzhCwQ/URK9gztFiUI/AAAAAAAADz4/2rHQHYaR_Ek/s1600/IMG_7796.jpg"};

  public static final String[] TECHNO_IMAGE = {
      "http://www.vintagesynth.com/roland/images/tb303big.jpg",
      "https://staging-thump-images.vice.com/images/2015/1/27/tresors-founder-wants-to-build-a-berlin-style-techno-club-in-detroit-does-the-city-need-it-1422362657487.jpg",
      "http://www.that-dj.com/wp-content/uploads/image/Deep%20Techno%20Club%20Industrial.jpg",
      "http://1.bp.blogspot.com/-59cMgzzhCwQ/URK9gztFiUI/AAAAAAAADz4/2rHQHYaR_Ek/s1600/IMG_7796.jpg" };

  public static final String[] HOUSE_DETAIL = { "Acid techno is a genre of techno that developed out of late 1980s Chicago acid house. Acid house was essentially house music made with a specific sound, obtained by using very distinctive instruments created mainly by Roland, such as the TB-303 for bass and lead sounds, and the TR-909 and TR-808 for percussion. Acid specifically refers to the use of the Roland TB-303, or any other synthesizer designed to emulate its unique sound. While modern electronic instruments have memory banks of different sounds or patches, these machines had to be manually set by adjusting control knobs. The acid sound was obtained by either setting these controls to extreme parameters, or manipulating these controls in real-time as the track was being recorded, something record producers would call tweaking. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
      "Detroit techno is a type of techno music that generally includes the first techno productions by Detroit-based artists during the 1980s and early 1990s. Detroit has been cited as the birthplace of techno. Prominent Detroit techno artists include Juan Atkins, Derrick May, and Kevin Saunderson. A distinguishing trait of Detroit techno is the use of analog synthesizers and early drum machines, particularly the Roland TR-909, or, in later releases, the use of digital emulation to create the characteristic sounds of those machines.",
      "Minimal techno is a minimalist subgenre of techno. It is characterized by a stripped-down aesthetic that exploits the use of repetition, and understated development. Minimal techno is thought to have been originally developed in the early 1990s by Detroit-based producers Robert Hood and Daniel Bell. By the early 2000s the term \'minimal\' generally described a style of techno that was popularised in Germany by labels such as Kompakt, Perlon, and Richie Hawtin\'s M-nus, amongst others.",
      "Techno is a form of electronic dance music that emerged in Detroit, Michigan, in the United States during the mid-to-late 1980s. The first recorded use of the word techno in reference to a specific genre of music was in 1988. Many styles of techno now exist, but Detroit techno is seen as the foundation upon which a number of subgenres have been built.",
      "" };


  public static final String[] TECHNO_DETAIL = { "Acid techno is a genre of techno that developed out of late 1980s Chicago acid house. Acid house was essentially house music made with a specific sound, obtained by using very distinctive instruments created mainly by Roland, such as the TB-303 for bass and lead sounds, and the TR-909 and TR-808 for percussion. Acid specifically refers to the use of the Roland TB-303, or any other synthesizer designed to emulate its unique sound. While modern electronic instruments have memory banks of different sounds or patches, these machines had to be manually set by adjusting control knobs. The acid sound was obtained by either setting these controls to extreme parameters, or manipulating these controls in real-time as the track was being recorded, something record producers would call tweaking. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
  "Detroit techno is a type of techno music that generally includes the first techno productions by Detroit-based artists during the 1980s and early 1990s. Detroit has been cited as the birthplace of techno. Prominent Detroit techno artists include Juan Atkins, Derrick May, and Kevin Saunderson. A distinguishing trait of Detroit techno is the use of analog synthesizers and early drum machines, particularly the Roland TR-909, or, in later releases, the use of digital emulation to create the characteristic sounds of those machines.",
  "Minimal techno is a minimalist subgenre of techno. It is characterized by a stripped-down aesthetic that exploits the use of repetition, and understated development. Minimal techno is thought to have been originally developed in the early 1990s by Detroit-based producers Robert Hood and Daniel Bell. By the early 2000s the term \'minimal\' generally described a style of techno that was popularised in Germany by labels such as Kompakt, Perlon, and Richie Hawtin\'s M-nus, amongst others.",
  "Techno is a form of electronic dance music that emerged in Detroit, Michigan, in the United States during the mid-to-late 1980s. The first recorded use of the word techno in reference to a specific genre of music was in 1988. Many styles of techno now exist, but Detroit techno is seen as the foundation upon which a number of subgenres have been built." };


}
